#!/usr/bin/env python3
"""
Spin up a new project from a cc_projects template.

Usage:
    uv run new-project.py                              # interactive picker
    uv run new-project.py flask-template my-app        # direct
    uv run new-project.py flask-template ~/projects/my-app
    uv run new-project.py --list                       # list templates
    uv run new-project.py flask-template my-app --no-uv  # skip uv setup
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent

# Directories/files to exclude when copying
EXCLUDE = {
    ".venv", "venv", "env", ".env",
    "__pycache__", ".pytest_cache", ".ruff_cache",
    "node_modules", ".next",
    ".git",
    "dist", "build",
    "temp",
    "uv.lock",  # regenerated fresh per project
}


def find_templates() -> list[Path]:
    """Return template directories — any subdirectory containing a CLAUDE.md."""
    return [
        d for d in sorted(REPO_ROOT.iterdir())
        if d.is_dir() and (d / "CLAUDE.md").exists() and d.name not in EXCLUDE
    ]


def print_templates(templates: list[Path]) -> None:
    print("\nAvailable templates:\n")
    for t in templates:
        readme = t / "README.md"
        description = ""
        if readme.exists():
            for line in readme.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#"):
                    description = line[:72]
                    break
        print(f"  {t.name:<30} {description}")
    print()


def copy_template(src: Path, dst: Path) -> None:
    def ignore(dir_path, contents):
        return {item for item in contents if item in EXCLUDE or item.endswith(".egg-info")}

    shutil.copytree(src, dst, ignore=ignore)


def pick_template(templates: list[Path]) -> Path:
    print_templates(templates)
    names = [t.name for t in templates]
    while True:
        choice = input("Template name: ").strip()
        if choice in names:
            return next(t for t in templates if t.name == choice)
        print(f"  Not found. Choose from: {', '.join(names)}")


def is_python_project(dst: Path) -> bool:
    return (dst / "requirements.txt").exists() or (dst / "pyproject.toml").exists()


def run(cmd: list[str], cwd: Path) -> bool:
    """Run a command, stream output, return True on success."""
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd)
    return result.returncode == 0


def setup_uv(dst: Path) -> None:
    """
    Set up a uv-managed Python environment in the new project.

    Strategy:
      1. If no pyproject.toml → uv init (creates one), then uv add deps from requirements.txt
      2. If pyproject.toml exists + requirements.txt exists → uv add -r requirements.txt
      3. If pyproject.toml exists, no requirements.txt → uv sync (install from existing toml)
      4. requirements-dev.txt → uv add --dev -r requirements-dev.txt
    """
    has_toml = (dst / "pyproject.toml").exists()
    has_req = (dst / "requirements.txt").exists()
    has_req_dev = (dst / "requirements-dev.txt").exists()

    print("\nSetting up uv environment...")

    # Step 1 — ensure pyproject.toml exists
    if not has_toml:
        project_name = dst.name.replace("-", "_").replace(" ", "_")
        ok = run(["uv", "init", "--no-readme", "--name", project_name], cwd=dst)
        if not ok:
            print("  Warning: uv init failed — skipping uv setup.")
            return
        # uv init creates a placeholder main.py — remove it if our template has its own
        placeholder = dst / "main.py"
        if placeholder.exists() and placeholder.read_text().strip() in (
            'def main():\n    print("Hello from ' + project_name + '!")\n\n\nif __name__ == "__main__":\n    main()',
            "# This file was generated by uv",
        ):
            placeholder.unlink()

    # Step 2 — add runtime deps
    if has_req:
        run(["uv", "add", "-r", "requirements.txt"], cwd=dst)
    else:
        run(["uv", "sync"], cwd=dst)

    # Step 3 — add dev deps
    if has_req_dev:
        run(["uv", "add", "--dev", "-r", "requirements-dev.txt"], cwd=dst)

    print("  uv setup complete. Virtual environment is in .venv/")


def print_next_steps(dst: Path) -> None:
    # Show Quick Start section from README
    readme = dst / "README.md"
    if readme.exists():
        lines = readme.read_text(encoding="utf-8").splitlines()
        section_lines: list[str] = []
        in_section = False
        for line in lines:
            if any(kw in line.lower() for kw in ("quick start", "getting started", "installation")):
                in_section = True
                section_lines = [line]
                continue
            if in_section:
                if line.startswith("## ") and section_lines:
                    break
                section_lines.append(line)
        if section_lines:
            print("\n" + "-" * 52)
            print("\n".join(section_lines[:20]).strip())
            print("-" * 52)

    has_venv = (dst / ".venv").exists()
    print(f"\nNext steps:")
    print(f"  cd '{dst}'")
    if has_venv:
        print(f"  uv run <entrypoint>        # run with managed env")
        print(f"  uv add <package>           # add a dependency")
        print(f"  uv add --dev <package>     # add a dev dependency")
    else:
        print(f"  uv run new-project.py --setup '{dst}'  # run uv setup later")
    print(f"  # Open in VSCode and launch Claude Code\n")


def do_setup_only(path_str: str) -> None:
    """Re-run uv setup on an existing project directory (--setup mode)."""
    dst = Path(path_str).expanduser().resolve()
    if not dst.exists():
        print(f"Error: '{dst}' does not exist.")
        sys.exit(1)
    setup_uv(dst)


def main():
    parser = argparse.ArgumentParser(
        description="Create a new project from a cc_projects template.",
    )
    parser.add_argument("template", nargs="?", help="Template directory name")
    parser.add_argument("destination", nargs="?", help="Destination path for the new project")
    parser.add_argument("--list", "-l", action="store_true", help="List available templates")
    parser.add_argument("--no-uv", action="store_true", help="Skip uv environment setup")
    parser.add_argument("--setup", metavar="PATH", help="Run uv setup on an existing project directory")
    args = parser.parse_args()

    if args.setup:
        do_setup_only(args.setup)
        return

    templates = find_templates()

    if args.list:
        print_templates(templates)
        return

    # Resolve template
    if args.template:
        names = [t.name for t in templates]
        if args.template not in names:
            print(f"Error: '{args.template}' is not a known template.")
            print(f"Available: {', '.join(names)}")
            sys.exit(1)
        src = next(t for t in templates if t.name == args.template)
    else:
        src = pick_template(templates)

    # Resolve destination
    if args.destination:
        dst = Path(args.destination).expanduser().resolve()
    else:
        suggestion = src.name.replace("-template", "")
        raw = input(f"Project directory [{suggestion}]: ").strip()
        dst = Path(raw or suggestion).expanduser().resolve()

    if dst.exists():
        print(f"Error: '{dst}' already exists.")
        sys.exit(1)

    print(f"\nCreating '{src.name}' -> '{dst}' ...")
    copy_template(src, dst)
    print(f"Done.")

    if not args.no_uv and is_python_project(dst):
        setup_uv(dst)

    print_next_steps(dst)


if __name__ == "__main__":
    main()
