# Generated by Django 6.0.3 on 2026-03-08 20:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AffectedGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("economic", "Economic"),
                            ("demographic", "Demographic"),
                            ("geographic", "Geographic"),
                            ("industry", "Industry"),
                            ("environmental", "Environmental"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("executive_order", "Executive Order"),
                            ("bill_sponsorship", "Bill Sponsorship"),
                            ("public_statement", "Public Statement"),
                            ("committee_action", "Committee Action"),
                            ("appointment", "Appointment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_issued", models.DateField(db_index=True)),
                ("summary", models.TextField()),
                ("full_text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date_issued"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=1000)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("government", "Government"),
                            ("news", "News"),
                            ("nonprofit", "Non-Profit"),
                            ("academic", "Academic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reliability_score",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DecisionAffectedGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("mixed", "Mixed"),
                            ("neutral", "Neutral"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("impact_summary", models.TextField(blank=True)),
                (
                    "estimated_people_affected",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "affected_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.affectedgroup",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.decision",
                    ),
                ),
            ],
            options={
                "unique_together": {("decision", "affected_group")},
            },
        ),
        migrations.AddField(
            model_name="decision",
            name="affected_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="decisions",
                through="tracker.DecisionAffectedGroup",
                to="tracker.affectedgroup",
            ),
        ),
        migrations.CreateModel(
            name="Politician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "party",
                    models.CharField(
                        choices=[
                            ("D", "Democrat"),
                            ("R", "Republican"),
                            ("I", "Independent"),
                            ("O", "Other"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("senate", "Senate"),
                            ("house", "House of Representatives"),
                            ("executive", "Executive"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("district", models.CharField(blank=True, max_length=10)),
                (
                    "bioguide_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "votesmart_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "opensecrets_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("bio", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("official_url", models.URLField(blank=True, max_length=500)),
                ("term_start", models.DateField(blank=True, null=True)),
                ("term_end", models.DateField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="tracker_pol_search__cd0b78_gin"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="decision",
            name="politician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="tracker.politician",
            ),
        ),
        migrations.CreateModel(
            name="FundingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("donor_name", models.CharField(max_length=500)),
                ("donor_category", models.CharField(blank=True, max_length=255)),
                ("amount_cents", models.BigIntegerField()),
                ("cycle_year", models.IntegerField(db_index=True)),
                (
                    "politician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_records",
                        to="tracker.politician",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-cycle_year", "-amount_cents"],
            },
        ),
        migrations.AddField(
            model_name="decision",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.source",
            ),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill_number", models.CharField(db_index=True, max_length=50)),
                ("bill_title", models.CharField(max_length=500)),
                ("vote_date", models.DateField(db_index=True)),
                (
                    "vote_choice",
                    models.CharField(
                        choices=[
                            ("Yea", "Yea"),
                            ("Nay", "Nay"),
                            ("Present", "Present"),
                            ("NotVoting", "Not Voting"),
                        ],
                        max_length=10,
                    ),
                ),
                ("congress_session", models.IntegerField(blank=True, null=True)),
                ("roll_call_number", models.IntegerField(blank=True, null=True)),
                (
                    "politician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="tracker.politician",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-vote_date"],
                "unique_together": {("politician", "bill_number", "vote_date")},
            },
        ),
    ]
